/**
 * @file synonyms.ts
 * @description Diccionario de equivalencias léxicas, términos automotrices venezolanos y errores fonéticos habituales.
 * 
 * [MERCADO VENEZUELA]
 * Mapea modelos de motos comunes (Bera SBR, Empire Horse, Keeway Owen, Suzuki GN/HJ),
 * modismos monetarios ('verdes', 'lechugas') y variaciones ortográficas de repuestos.
 */

export const SYNONYMS: Record<string, string> = {
  // 🛞 Insumos para Caucheras
  'parche': 'parches',
  'parches': 'parches',
  'parxe': 'parches',
  'parxes': 'parches',
  'parchar': 'parches',
  'rema': 'parches',
  'remafrio': 'parches',
  'parche frio': 'parches',
  'pega': 'pega',
  'pegamento': 'pega',
  'cemento': 'pega',
  'valvula': 'valvulas',
  'gusanillo': 'valvula',
  'tarugo': 'tarugos',
  'tarugos': 'tarugos',
  'mecha': 'tarugos',
  'mechas': 'tarugos',
  'plomo': 'plomos',
  'plomos': 'plomos',
  'balanceo': 'plomos',
  'contrapeso': 'plomos',
  'contrapesos': 'plomos',
  'tripa': 'tripa',
  'tripas': 'tripa',
  'camara': 'tripa',
  'camaras': 'tripa',

  // 🏍️ Repuestos para Moto
  'arrastre': 'arrastre',
  'cadena': 'cadena',
  'cadenas': 'cadena',
  'piñon': 'piñon',
  'piñones': 'piñon',
  'corona': 'corona',
  'coronas': 'corona',
  'catalina': 'corona',
  'pastilla': 'pastillas',
  'pastillas': 'pastillas',
  'pastiya': 'pastillas',
  'pastiyas': 'pastillas',
  'balata': 'pastillas',
  'balatas': 'pastillas',
  'banda': 'bandas',
  'bandas': 'bandas',
  'freno': 'freno',
  'frenos': 'freno',
  'bujia': 'bujia',
  'bujias': 'bujia',
  'bujya': 'bujia',
  'bujyas': 'bujia',
  'aceite': 'aceite',
  'aceites': 'aceite',
  'aciete': 'aceite',
  'aciite': 'aceite',
  '4t': '4t',
  '2t': '2t',
  'croche': 'croche',
  'clutch': 'croche',
  'embrague': 'croche',
  'guaya': 'guaya',
  'guayas': 'guaya',
  'bateria': 'bateria',
  'baterias': 'bateria',

  // 🎽 Accesorios para Moto
  'puño': 'puños',
  'puños': 'puños',
  'malla': 'malla',
  'mallas': 'malla',
  'pulpo': 'malla',
  'pulpos': 'malla',
  'retrovisor': 'retrovisores',
  'retrovisores': 'retrovisores',
  'espejo': 'retrovisores',
  'espejos': 'retrovisores',
  'candado': 'candado',
  'candados': 'candado',
  'spray': 'lubricante',

  // 📦 Otros Productos (Mantenimiento general)
  'refrigerante': 'refrigerante',
  'refrigerantes': 'refrigerante',
  'coolant': 'refrigerante',
  'aditivo': 'aditivo',
  'aditivos': 'aditivo',
  'inyectores': 'aditivo',
  'limpiador': 'aditivo',
  'plumilla': 'plumillas',
  'plumillas': 'plumillas',
  'limpiaparabrisas': 'plumillas',
  'cepillo': 'plumillas',
  'cepillos': 'plumillas',
  'bombillo': 'bombillos',
  'bombillos': 'bombillos',
  'faro': 'bombillos',
  'faros': 'bombillos',
  'led': 'led',
  'luces': 'led',
  'luz': 'led',
  'silicon': 'silicon',
  'fusible': 'fusibles',
  'fusibles': 'fusibles',
  'repuesto': 'repuestos',

  // 💵 Monedas y modismos locales
  'verdes': 'dolares',
  'verde': 'dolares',
  'lechugas': 'dolares',
  'divisa': 'dolares',
  'divisas': 'dolares',
  'dolar': 'dolares',

  // 🛞 Neumáticos y llantas
  'caucho': 'caucho',
  'cauchos': 'caucho',
  'llanta': 'caucho',
  'llantas': 'caucho',
  'neumatico': 'caucho',
  'neumaticos': 'caucho',
  'sellomatic': 'sellomatic',

  // 🏍️ Marcas y modelos automotrices de alta circulación en Venezuela
  'sbr': 'sbr',
  'horse': 'horse',
  'owen': 'owen',
  'arsen': 'arsen',
  'gn': 'gn',
  'gn125': 'gn',
  'hj': 'hj',
  'speed': 'speed',
  'tx': 'tx',
  'tx200': 'tx',
  'kway': 'keeway',
  'keeway': 'keeway',
  'jaguar': 'jaguar',
  'bera': 'bera',
  'empire': 'empire',
  'suzuki': 'suzuki',
  'ngk': 'ngk',
  'motul': 'motul',
  'sky': 'sky',

  // 🏍️ Términos de la página web (cascos y marcas)
  'casco': 'casco',
  'cascos': 'casco',
  'coraza': 'casco',
  'corazas': 'casco',
  'shaft': 'shaft',
  'axxis': 'axxis',
  'moxul': 'moxul',
  'edge': 'edge',
  'michelin': 'michelin',
  'ceat': 'ceat',
  'eurogrip': 'eurogrip',
  'timsun': 'timsun',
  'euromina': 'euromina',
  'macuro': 'macuro',
  'roshfrans': 'roshfrans',
  'ipone': 'ipone',
  'pdv': 'pdv',
  'inca': 'inca',
  'ultralub': 'ultralub'
};

export default SYNONYMS;
