// Diccionario de equivalencias y sinónimos comunes de cauchera, motos y otros productos en Venezuela
const SYNONYMS = {
  // 🛞 Insumos para Caucheras
  'parche': 'parches',
  'pega': 'pega',
  'pegamento': 'pega',
  'cemento': 'pega',
  'valvula': 'valvulas',
  'gusanillo': 'valvula',
  'tarugo': 'tarugos',
  'tarugos': 'tarugos',
  'mecha': 'tarugos',
  'mechas': 'tarugos',
  'plomo': 'plomos',
  'plomos': 'plomos',
  'balanceo': 'plomos',
  'contrapeso': 'plomos',
  'contrapesos': 'plomos',
  'tripa': 'tripa',
  'tripas': 'tripa',
  'camara': 'tripa',
  'camaras': 'tripa',

  // 🏍️ Repuestos para Moto
  'arrastre': 'arrastre',
  'cadena': 'cadena',
  'cadenas': 'cadena',
  'piñon': 'piñon',
  'piñones': 'piñon',
  'corona': 'corona',
  'coronas': 'corona',
  'catalina': 'corona',
  'pastilla': 'pastillas',
  'pastillas': 'pastillas',
  'balata': 'pastillas',
  'balatas': 'pastillas',
  'banda': 'bandas',
  'bandas': 'bandas',
  'frenos': 'pastillas',
  'bujia': 'bujia',
  'bujias': 'bujia',
  'aceite': 'aceite',
  'aceites': 'aceite',
  '4t': '4t',
  '2t': '2t',
  'croche': 'croche',
  'clutch': 'croche',
  'embrague': 'croche',
  'guaya': 'guaya',
  'guayas': 'guaya',
  'bateria': 'bateria',
  'baterias': 'bateria',

  // 🎽 Accesorios para Moto
  'puño': 'puños',
  'puños': 'puños',
  'gomas': 'puños',
  'malla': 'malla',
  'mallas': 'malla',
  'pulpo': 'malla',
  'pulpos': 'malla',
  'retrovisor': 'retrovisores',
  'retrovisores': 'retrovisores',
  'espejo': 'retrovisores',
  'espejos': 'retrovisores',
  'candado': 'candado',
  'candados': 'candado',
  'spray': 'lubricante',

  // 📦 Otros Productos (Mantenimiento general)
  'refrigerante': 'refrigerante',
  'refrigerantes': 'refrigerante',
  'coolant': 'refrigerante',
  'aditivo': 'aditivo',
  'aditivos': 'aditivo',
  'inyectores': 'aditivo',
  'limpiador': 'aditivo',
  'plumilla': 'plumillas',
  'plumillas': 'plumillas',
  'limpiaparabrisas': 'plumillas',
  'cepillo': 'plumillas',
  'cepillos': 'plumillas',
  'bombillo': 'bombillos',
  'bombillos': 'bombillos',
  'faro': 'bombillos',
  'faros': 'bombillos',
  'led': 'led',
  'luces': 'led',
  'luz': 'led',
  'silicon': 'silicon',
  'fusible': 'fusibles',
  'fusibles': 'fusibles',
  'repuesto': 'repuestos',

  // 💵 Monedas y modismos
  'verdes': 'dolares',
  'verde': 'dolares',
  'lechugas': 'dolares',
  'divisa': 'dolares',
  'divisas': 'dolares',
  'dolar': 'dolares',

  // 🛞 Neumáticos y llantas
  'caucho': 'caucho',
  'cauchos': 'caucho',
  'llanta': 'caucho',
  'llantas': 'caucho',
  'neumatico': 'caucho',
  'neumaticos': 'caucho',
  'sellomatic': 'sellomatic',

  // 🏍️ Marcas y Modelos populares en Venezuela
  'sbr': 'sbr',
  'horse': 'horse',
  'owen': 'owen',
  'arsen': 'arsen',
  'gn': 'gn',
  'gn125': 'gn',
  'hj': 'hj',
  'speed': 'speed',
  'tx': 'tx',
  'tx200': 'tx',
  'kway': 'keeway',
  'keeway': 'keeway',
  'jaguar': 'jaguar',
  'bera': 'bera',
  'empire': 'empire',
  'suzuki': 'suzuki',
  'ngk': 'ngk',
  'motul': 'motul',
  'sky': 'sky'
};

module.exports = { SYNONYMS };
